### ISSUE TITLE
consistency (with s3 blobstore resource) with respect to file placement

### ISSUE THREAD

**Issue by eitansuez** [pivotal-cf/azure-blobstore-resource#16]
i have gone through the exercise of retrofitting the pipelines from platform automation (see http://docs.pivotal.io/platform-automation/v2.1/reference/pipeline.html ) to use the azure blobstore resource instead of the s3 blobstore resource.

in the process, i discovered a difference in behavior between the two resource implementations which i'd like to describe next.

in the first pipeline (retrieving external dependencies), take for example the resource `pas-stemcell`.
its regexp specifies a subdirectory `pas-stemcell/`.

in the subsequent pipeline ("installing ops mgr and tiles"), we see pas-stemcell again, with the same regexp.

when the job named 'upload-stemcells' runs, the task named 'upload-pas-stemcell' fails with a "file not found".  when i concourse hijacked into the container, i discovered that the path to the stemcell inside the container was pas-stemcell/pas-stemcell/{stemcellfilename}.  i.e. it had a nested subdirectory.  not so when i use the s3 blobstore resource.

i worked around the issue by adding a step to move the file, like so:

```
      - task: move-file-shim
        config:
          platform: linux
          inputs:
          - name: pas-stemcell
          run:
            path: /bin/sh
            args:
            - -c
            - mv pas-stemcell/pas-stemcell/* wellplaced-stemcell/
          outputs:
          - name: wellplaced-stemcell
```

and then in the subsequent task, i replaced the `input_mapping` -> `stemcell` to the output `wellplaced-stemcell`.

i realized a more elegant solution is to consider revising the blobstore resource's implementation to match whatever the s3 resource currently does.

i'm not yet familiar enough with go and with this project to contribute a PR just yet.  but in case this is easily captured via a couple of unit tests and easily fixed, at least i could put this on your radar.

thanks in advance for your consideration.
