### ISSUE TITLE
Regexp issue with platform-automation artifiacts

### ISSUE THREAD

**Issue by marijenk** [pivotal-cf/azure-blobstore-resource#24]
We are experiencing some inconsistencies when using the `regexp` in the source configuration when retrieving artifacts from our Blobstore in Azure:

Below is an snippet of the files in the blobstore:

![image (8)](https://user-images.githubusercontent.com/42005626/62395606-c4734800-b53e-11e9-9843-7956036d8d65.png)

Below is the example of our configuration:

```
resources:
- name: platform-automation-image
 type: azure-blobstore
 source:
   storage_account_name: ((storage_account_name))
   storage_account_key: ((storage_account_key))
   container: ((container))
   regexp: platform-automation-image-(.*).tgz

- name: platform-automation-tasks
 type: azure-blobstore
 source:
   storage_account_name: ((storage_account_name))
   storage_account_key: ((storage_account_key))
   container: ((container))
   regexp: platform-automation-tasks-(.*).zip
```

Below is the error we are seeing in Concourse:

![image (7)](https://user-images.githubusercontent.com/42005626/62395616-d0f7a080-b53e-11e9-8db9-e3435c395a63.png)

When we initially flew up the pipeline, this was working just fine. We ran a couple of jobs multiple times with no issues. Now all of a sudden, the resource isn't finding the blob anymore for some odd reason. We've deleted the pipeline and re-flown it up but still no luck.

As a workaround, we switched to using the `versioned_file` source parameter by giving the explicit file name. This works however, we don't want to do this in the long term due to newer versions of this being released.

**Comment by christianang** [comment]
Interesting. This does seem really odd. I did push a new image, but that just bumped a dependency, and didn't modify any of the regexp code.

Did a quick test using a similar naming scheme and everything seems to work. This is using the latest image in `pcfabr/azure-blobstore-resource` correct? Is there anywhere else you are using the `regexp` pattern, that is working, or are they all failing?

This is what I tried (I also uploaded a blob called `platform-automation-image-(.*).txt`):
```yaml
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

resources:
  - name: azure-blobstore-resource
    type: git
    source:
      uri: https://github.com/pivotal-cf/azure-blobstore-resource.git
      branch: master

  - name: configuration
    type: azure-blobstore
    source:
      storage_account_name: ((storage_account_name))
      storage_account_key: ((storage_account_key))
      container: ((container))
      regexp: platform-automation-image-(.*).txt

jobs:
- name: print-config
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
    - get: configuration
  - task: print-config
    file: azure-blobstore-resource/example/tasks/print-config/task.yml
    params:
      CONFIGURATION_FILENAME: platform-automation-image-*.txt
```

**Comment by poligraph** [comment]
@christianang I have created sample pipeline to copy pivnet stemcells to Azure blobstore and now getting the same error

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2019/08/07 16:17:18 failed to get latest version from regexp: no matching blob found for regexp: bosh-stemcell-*.tgz
```

pipeline lives here
https://plane.dev.azure-rnd.xyz/teams/main/pipelines/azure-blobstore

and code 
```
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tags: latest-final

resources:
- name: platform-automation-image
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    regexp: platform-automation-image-(.*).tgz

- name: platform-automation-tasks
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((container))
    regexp: platform-automation-tasks-(.*).zip

- name: azure-stemcell
  type: azure-blobstore
  public: true
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: ((stemcell-container))
    regexp: bosh-stemcell-*.tgz

- name: stemcell-315
  public: true
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: stemcells-ubuntu-xenial
    product_version: 315.*
    sort_by: semver

- name: stemcell-250
  public: true
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: stemcells-ubuntu-xenial
    product_version: 250.*
    sort_by: semver

- name: stemcell-170
  type: pivnet
  public: true
  source:
    api_token: ((pivnet_token))
    product_slug: stemcells-ubuntu-xenial
    product_version: 170.*
    sort_by: semver

- name: 5m
  type: time
  source: {interval: 5m}

jobs:
- name: job1
  public: true
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: 5m
      trigger: true
    - get: stemcell-315
  - put: azure-stemcell
    params:
      file: stemcell-315/bosh-stemcell-*.tgz
- name: job2
  public: true
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: 5m
      trigger: true
    - get: stemcell-250
  - put: azure-stemcell
    params:
      file: stemcell-250/bosh-stemcell-*.tgz
- name: job3
  public: true
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: 5m
      trigger: true
    - get: stemcell-170
  - put: azure-stemcell
    params:
      file: stemcell-170/bosh-stemcell-*.tgz
```
