### ISSUE TITLE
How do I avoid the "failed to copy blob: context deadline exceeded" error?

### ISSUE THREAD

**Issue by aullom1** [pivotal-cf/azure-blobstore-resource#30]
I have 15GB blob that I am trying to download, but I keep getting the "failed to copy blob: context deadline exceeded" error.  I have successfully downloaded smaller blobs, so I know I am doing it the right way.  The failures always seems to happen at right around 10 minutes (give or take 30 seconds).

I have tried bumping the retry_timeout to 60m and setting the block_size to 50 and 100.

```yaml
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
resources:
- name: pas-product
  type: azure-blobstore
  check_every: 4h
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: tile-downloads
    regexp: srt-(((pas_major_minor_version)))-(.*).pivotal
    block_size: 50
    retry:
      try_timeout: "60m"
jobs:
- name: upload-and-stage-pas
  serial: true
  plan:
  - aggregate:
    - get: pas-product
      params:
        globs:
        - "srt-*"
  - task: test-config-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: sandyg1/om-cred-auto
      run:
        path: sh
        args:
        - -ec
        - |
           ls -lah
```

**Comment by aullom1** [comment]
It might have something to do with the version I am on.  v4.2.1 exhibits the problem, but when I try the latest (locally) it doesn't error out.  Also, when 4.2.1 does error out, it appears to have already allocated 15GB for the blob, and that space isn't being freed up.

**Comment by christianang** [comment]
The `block_size` is a bit unintuitive right now in that the value is in bytes not megabytes (which in hindsight it probably should of been). Made an issue to address that separately: https://github.com/pivotal-cf/azure-blobstore-resource/issues/31.

However, I don't think that would fix the issue you are seeing. I do notice that the `try_timeout` is set on the `source` instead of the `params` on the `get: pas-product`. If you were to move the `try_timeout` to `params` does the context deadline exceeded error still occur?

**Comment by aullom1** [comment]
@christianang Moving the `try_timeout` seems to have fixed the issue.  The `get` looks like this now.

```yaml
jobs:
- name: upload-and-stage-pas
  serial: true
  plan:
  - aggregate:
    - get: pas-product
      params:
        globs:
        - "srt-*"
        retry:
          try_timeout: 60m
```
