### ISSUE TITLE
Regexp broken if Azure container contains a folder with more that one file in it

### ISSUE THREAD

**Issue by ckunst** [pivotal-cf/azure-blobstore-resource#36]
The way to reproduce:
Create an Azure container with a structure containing a folder and more than one file inside of the folder in addition to files located in the root of the container.
Ex:

<container_name>
  - <folder_name>
      - file_in_folder_a-1.2.3.tgz
      - file_in_folder_b-1.3.4.tgz
  -  file_in_root_a-1.2.3.tgz
  - file_in_root_b-1.2.4.tgz

With a container file/folder structure as depicted above, the capturing group regex is not working anymore.
Ex: file_in_root_a-(.*).tgz
I had only a limited amount of time to troubleshoot but it looks like the API call/ go library is returning an empty array in this case so the root cause might reside in there.

**Comment by christianang** [comment]
I attempted to reproduce this unsuccessfully. I created a similar folder structure.

<img width="399" alt="Screen Shot 2020-02-11 at 5 29 38 PM" src="https://user-images.githubusercontent.com/539826/74294886-271a7d00-4cf4-11ea-8216-fd68e12a0cae.png">
<img width="348" alt="Screen Shot 2020-02-11 at 5 29 45 PM" src="https://user-images.githubusercontent.com/539826/74294888-27b31380-4cf4-11ea-9a44-9f537d63cfec.png">

And used the following pipeline (modified the example pipeline):

```
resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

resources:
  - name: azure-blobstore-resource
    type: git
    source:
      uri: https://github.com/pivotal-cf/azure-blobstore-resource.git
      branch: master

  - name: configuration
    type: azure-blobstore
    source:
      storage_account_name: ((storage_account_name))
      storage_account_key: ((storage_account_key))
      container: ((container))
      regexp: file_in_root_a-(.*).txt

jobs:
- name: print-config
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
    - get: configuration
  - task: print-config
    file: azure-blobstore-resource/example/tasks/print-config/task.yml
    params:
      CONFIGURATION_FILENAME: file_in_root_a-*

- name: write-config
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
  - task: write-config
    file: azure-blobstore-resource/example/tasks/write-config/task.yml
    params:
      CONFIGURATION_FILENAME: my-file
      APPEND_TIMESTAMP_ON_FILENAME: 1
  - put: configuration
    params:
      CONFIGURATION_FILENAME: file_in_root_a-*
```

The check ran successfully and so did the job. Let me know if my setup looks off.

Is this consistently failing for you or is it intermittent? Did this use to work at some point or did it never work? Trying to narrow down the possibilities.

**Comment by ckunst** [comment]
Indeed it seems that the subfolder assumption was a red herring. The issue occurred today again after we cleaned the structure to be flat. My current assumption is that it has to do with overwriting files based on the following observation:
- We have a download-products pipeline that is downloading resources from Pivnet every 24 hrs.
- The pipeliner run last night and has "overwritten" the files available in the Azure container.
- As a consequence, the regex stopped working
- I deleted manually only the files that were "overwritten" by the download-products pipeline
- As a consequence, the regex started to work again
- I started the download-products pipeline again and the new files were copied from Pivnet to the Azure container
- The regex is still working

Now I paused the download pipeline as I have to be unblocked in order to unblock the stories that were blocked by it.
Can you check if you can reproduce the above behavior on your lab?
Thank you!

**Comment by christianang** [comment]
I changed my pipeline to overwrite the file e.g

```
- name: write-config
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
  - task: write-config
    file: azure-blobstore-resource/example/tasks/write-config/task.yml
    params:
      CONFIGURATION_FILENAME: file_in_root_a-1.2.3.txt
  - put: configuration
    params:
      file: configuration/file_in_root_a-1.2.3.txt
```

Still haven't been able to reproduce the issue.

A couple questions to help potentially narrow this down:
1. Is it the check that is failing or the get within a job?
1. If it is the check. The resource ignores files that are currently copying, is it failing after the download-products pipeline is done or only when it is running?
1. I wrote a little program to list blobs using the same code as the resource. Can you run it and see if the api call to list blobs is working as expected i.e you see the expected files? Hopefully seeing the json output of the list blobs call can shed some light on what is happening.

```
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/Azure/azure-sdk-for-go/storage"
	"github.com/pivotal-cf/azure-blobstore-resource/azure"
)

func main() {
	storageAccountName := os.Args[1]
	storageAccountKey := os.Args[2]
	container := os.Args[3]

	azureClient := azure.NewClient(
		storage.DefaultBaseURL,
		storageAccountName,
		storageAccountKey,
		container,
	)

	blobs := []storage.Blob{}
	marker := ""

	for {
		blobListResponse, err := azureClient.ListBlobs(storage.ListBlobsParameters{
			Include: &storage.IncludeBlobDataset{
				Snapshots: true,
				Copy:      true,
			},
			Marker: marker,
		})

		if err != nil {
			panic(err)
		}

		for _, blob := range blobListResponse.Blobs {
			blobs = append(blobs, blob)
		}

		marker = blobListResponse.NextMarker
		if marker == "" || len(blobListResponse.Blobs) == 0 {
			break
		}
	}

	blobsJson, err := json.Marshal(blobs)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(blobsJson))
}
```

To run:
```
go run main.go <STORAGE_ACCOUNT_NAME> <STORAGE_ACCOUNT_KEY> <CONTAINER>
```
