### ISSUE TITLE
Azure China Cloud is not supported

### ISSUE THREAD

**Issue by RomRider** [pivotal-cf/azure-blobstore-resource#5]
Hi there,

We're trying to use this resource with Azure China and it fails to check the resource because the base URL of the blobstore is hardcoded and by default is `blob.core.windows.net`.
In Azure China, this URL should be `blob.core.windows.cn`.

There should be a way to provide an input to define which Azure you want to use (defaulting to AzureCloud) like in this resource: https://github.com/pivotal-cloudops/azure-blobstore-concourse-resource

The error you'd get by using this resource against Azure China Cloud is:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2018/11/05 08:21:26 failed to get latest version: Get https://BLOBSTORENAME.blob.core.windows.net/XXXXXXXX?comp=list&include=snapshots&prefix=FILE.NAME&restype=container: dial tcp: lookup BLOBSTORENAME.blob.core.windows.net on 168.63.129.16:53: no such host
```

Thanks for your help.
CC: @lakshmantgld @keliangneu

**Comment by christianang** [comment]
Thanks for bringing this up. I've added a new `base_url` param in the source configuration. This should be set to `core.windows.cn` in your case.

E.g:

```
resources:
  - name: terraform-state
    type: azure-blobstore
    source:
      base_url: core.windows.cn
      storage_account_name: {{storage_account_name}}
      storage_account_key: {{storage_account_key}}
      container: {{container}}
      versioned_file: terraform.tfstate
```

If not set it will default to the normal Azure Public Cloud: `core.windows.net`
